### ISSUE TITLE
set-output` command is deprecated

### ISSUE THREAD

**Issue by PittBie** [pavi2410/html-preview-action#16]
When trying this action I always get this response:

Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1393" alt="Bildschirmfoto 2024-08-21 um 22 45 00" src="https://github.com/user-attachments/assets/a206eaa4-6c67-4919-b5db-b1729f4ea8eb">

Am I doing something wrong?

**Comment by pavi2410** [comment]
This is true. This action hasn't been updated for a while...

**Comment by pavi2410** [comment]
https://github.com/pavi2410/html-preview-action/releases/tag/v3
