### ISSUE TITLE
Getting ##[error]Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by Nathaniel-A** [pavi2410/html-preview-action#5]
Hi, tried using your code for github actions via marketplace, getting the following error while trying to build and run my html. Have you encountered the same?

Run pavi2410/html-preview-action@v1a
  with:
    msg: Click here to preview HTML page in browser
    html_file: docs/html/index.html
    gh_token: ***

##[error]Cannot read property 'number' of undefined

**Comment by pavi2410** [comment]
First of all, thanks for using this Action.

Regarding the error, I think this is the cause of it
https://github.com/pavi2410/html-preview-action/blob/380ab8301465549934d5a27f4430bb28ab770057/index.js#L14

This can happen if the Action is not run from a PR. Can I check your workflow file?

BTW, I have thought of removing the comment system from this Action and let users use another comment Action from the marketplace.

**Comment by Nathaniel-A** [comment]
Thanks, yes figured out that the action was being run on "push" rather than a PR hence the issue
