### ISSUE TITLE
proper documentation 

### ISSUE THREAD

**Issue by Douglasokolaa** [pavi2410/html-preview-action#6]
can we please get proper documentation on how to use?

**Comment by pavi2410** [comment]
There isn't much to know how to use this action. This action, when run from a PR, sends a comment on the same PR with the link to the preview of the HTML file specified with the `html_file` argument. This action uses https://github.com/htmlpreview/htmlpreview.github.com to provide the links. Besides, you can customize the text format that is sent with the PR comment with the `msg` argument.

An example of its usage is present here: https://github.com/pavi2410/html-preview-action/blob/380ab8301465549934d5a27f4430bb28ab770057/.github/workflows/test.yml
You can also see this "Action" in action here: #1 

To know more about the available arguments/inputs, refer to this file: https://github.com/pavi2410/html-preview-action/blob/380ab8301465549934d5a27f4430bb28ab770057/action.yml

**Comment by Douglasokolaa** [comment]
Thanks. followed the guide but i got this error 

  **Get HTML preview link0s**
`##[error]Fail to load /home/runner/work/gateouse/gateouse/./action.yml
`
`##[error](Line: 1, Col: 1): A sequence was not expected
`
`##[error](Line: 1, Col: 1): A sequence was not expected
`
`##[error]Unexpected type 'SequenceToken' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
`
`##[error]Fail to load /home/runner/work/gateouse/gateouse/./action.yml
`
see [the this action](https://github.com/Douglasokolaa/gateouse/pull/4/checks?check_run_id=561834459)

**Comment by pavi2410** [comment]
I saw your repo's .github/workflows/test.yml file and found that it doesn't use this action. You can take a look at this file https://github.com/pavi2410/html-preview-action/blob/380ab8301465549934d5a27f4430bb28ab770057/.github/workflows/test.yml

**Comment by mkczyk** [comment]
I'm stuck with the configuration of this action.

I [add](https://github.com/mkczyk/test-experiment/blob/f2d89954a39fe4d2eb02188ba8a7042f29b8d295/.github/workflows/html-preview.yml) GitHub Action:

```
name: CI

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: 
      - "**"

  html_preview-job:
    - name: HTML Preview
      uses: pavi2410/html-preview-action@v2
```

And when I push commit or make PR it's [triggered](https://github.com/mkczyk/test-experiment/runs/836812857?check_suite_focus=true):
![image](https://user-images.githubusercontent.com/11051213/86512857-dff96980-be05-11ea-9d29-fcf8e8a601dc.png)

But I [don't see](https://github.com/mkczyk/test-experiment/pull/3) comment of github-actions bot:
![image](https://user-images.githubusercontent.com/11051213/86512900-1cc56080-be06-11ea-8e46-e46e24c946de.png)

(I expected comment like [that you showed](https://github.com/pavi2410/html-preview-action/pull/1).)

**Comment by pavi2410** [comment]
@mkczyk Please refer to this [commit](https://github.com/pavi2410/html-preview-action/commit/74762dfaef4e0dd0f6a8c102409d18492986dee7). This tries to replicate v1 behavior
